export const initialPerfumes = [
    { id: 1, name: "Ange ou Demon", price: '1 manat' },
    { id: 2, name: "Amor", price: '1 manat' },
    { id: 3, name: "Zəm-Zəm", price: '1 manat' },
    { id: 4, name: "Hermes", price: '1 manat' },
    { id: 5, name: "Dunhill", price: '1 manat' },
    { id: 6, name: "Victoria's Secret Bomshell", price: '1 manat' },
    { id: 7, name: "Shahrizad", price: '1 manat' },
    { id: 8, name: "Lucia", price: '1 manat' },
    { id: 9, name: "Antonio Banderas", price: '1 manat' },
    { id: 10, name: "Polo Blue", price: '1 manat' },
    { id: 11, name: "Armani Base", price: '1 manat' },
    { id: 12, name: "Armani Si", price: '1 manat' },
    { id: 13, name: "Jasmin", price: '1 manat' },
    { id: 14, name: "Chanel Chance", price: '1 manat' },
    { id: 15, name: "Egoiste (Chanel)", price: '1 manat' },
    { id: 16, name: "Eclat Sport (men)", price: '1 manat' },
    { id: 17, name: "Eclat Lanvin", price: '1 manat' },
    { id: 18, name: "Today", price: '1 manat' },
    { id: 19, name: "Dima Bilan", price: '1 manat' },
    { id: 20, name: "Coco Mademoiselle", price: '1 manat' },
    { id: 21, name: "Chrome Arraro", price: '1 manat' },
    { id: 22, name: "Chanel Sport", price: '1 manat' },
    { id: 23, name: "Chanel Blue", price: '1 manat' },
    { id: 24, name: "Versage Eros", price: '1 manat' },
    { id: 25, name: "Versage Crystal Bright", price: '1 manat' },
    { id: 26, name: "Versage Versus", price: '1 manat' },
    { id: 27, name: "Tom Ford Black Orchid", price: '1 manat' },
    { id: 28, name: "Tom Ford Tobacco Vanille", price: '1 manat' },
    { id: 29, name: "L`Eau Par Kenzo", price: '1 manat' },
    { id: 30, name: "Invictus", price: '1 manat' },
    { id: 31, name: "One Million", price: '1 manat' },
    { id: 32, name: "Lady Million", price: '1 manat' },
    { id: 33, name: "Lacoste Essential", price: '1 manat' },
    { id: 34, name: "Lacoste Femme", price: '1 manat' },
    { id: 35, name: "Lacoste Red", price: '1 manat' },
    { id: 36, name: "Gucci Ruch", price: '1 manat' },
    { id: 37, name: "D.G Light Blue", price: '1 manat' },
    { id: 38, name: "D.G The One", price: '1 manat' },
    { id: 39, name: "D.G L'imperatrice", price: '1 manat' },
    { id: 40, name: "Nina Ricci", price: '1 manat' },
    { id: 41, name: "J'adore (DIOR)", price: '1 manat' },
    { id: 42, name: "Chanel Tender", price: '1 manat' },
    { id: 43, name: "Narciso for her", price: '1 manat' },
    { id: 44, name: "Trussardi Donna", price: '1 manat' },
    { id: 45, name: "Trussardi Uomo", price: '1 manat' },
    { id: 46, name: "Trussardi My Land", price: '1 manat' },
    { id: 47, name: "Cigar", price: '1 manat' },
    { id: 48, name: "Jagler", price: '1 manat' },
    { id: 49, name: "Caldior (for women)", price: '1 manat' },
    { id: 50, name: "Hugo Boss", price: '1 manat' },
    { id: 51, name: "Explore", price: '1 manat' },
    { id: 52, name: "Cool Water", price: '1 manat' },
    { id: 53, name: "Acqua di Gio (men)", price: '1 manat' },
    { id: 54, name: "Arman Code", price: '1 manat' },
    { id: 55, name: "Fendi", price: '1 manat' },
    { id: 56, name: "Lanvin Marry", price: '1 manat' },
    { id: 57, name: "Chloe Love Story", price: '1 manat' },
    { id: 58, name: "Libre", price: '2 manat' },
    { id: 59, name: "Anna Sui", price: '2 manat' },
    { id: 60, name: "Amo Ferragamo", price: '2 manat' },
    { id: 61, name: "L'interdit", price: '2 manat' },
    { id: 62, name: "Ricardo Veron", price: '2 manat' },
    { id: 63, name: "My Burberry", price: '2 manat' },
    { id: 64, name: "My Way", price: '2 manat' },
    { id: 65, name: "Armani Cashmere", price: '2 manat' },
    { id: 66, name: "ELIE SAAB", price: '2 manat' },
    { id: 67, name: "Stronger with You", price: '2.50 manat' },
    { id: 68, name: "Poudre", price: '2 manat' },
    { id: 69, name: "Good Girl", price: '2 manat' },
    { id: 70, name: "Oligarch", price: '3 manat' },
    { id: 71, name: "Prada Carbon", price: '2 manat' },
    { id: 72, name: "Baccarat 540", price: '2.50 manat' },
    { id: 73, name: "Narcotique sadə", price: '1.5 manat' },
    { id: 74, name: "Lancome Midnight", price: '2 manat' },
    { id: 75, name: "Lancome La Bella", price: '1 manat' },
    { id: 76, name: "212 men", price: '1 manat' },
    { id: 77, name: "Parfume", price: '1 manat' },
    { id: 78, name: "Ganymede", price: '3 manat' },
    { id: 79, name: "Aventus Delux", price: '4 manat' },
    { id: 80, name: "Aventus Sadə", price: '1.5 manat' },
    { id: 81, name: "Aventus Noir", price: '4 manat' },
    { id: 82, name: "Molecul Delux", price: '4 manat' },
    { id: 83, name: "Molecul Sadə", price: '2 manat' },
    { id: 84, name: "Accento Delux", price: '4 manat' },
    { id: 85, name: "Accento Sadə", price: '1.5 manat' },
    { id: 86, name: "Erba Pura Delux", price: '4 manat' },
    { id: 87, name: "Erba Pura Sadə", price: '1.5 manat' },
    { id: 88, name: "Bulgari Tygar Delux", price: '4 manat' },
    { id: 89, name: "Bulgari Tygar Sadə", price: '2 manat' },
    { id: 90, name: "Bulgari ou The Noir", price: '2 manat' },
    { id: 91, name: "Giordani Gold", price: '2 manat' },
    { id: 92, name: "Kilian Good Girl", price: '2 manat' },
    { id: 93, name: "L'lmensite", price: '4 manat' },
    { id: 94, name: "Afternoon Swim", price: '4 manat' },
    { id: 95, name: "IMAGIONATION", price: '4 manat' },
    { id: 96, name: "Stellar Times", price: '4 manat' },
    { id: 97, name: "Pateholi", price: '4 manat' },
    { id: 98, name: "Red Tobacco", price: '1.5 manat' },
    { id: 99, name: "Orris Sandalwood", price: '2 manat' },
    { id: 100, name: "Afgano Delux", price: '3 manat' },
    { id: 101, name: "Afgano Sadə", price: '1.5 manat' },
    { id: 102, name: "Shiseido Zen", price: '2 manat' },
    { id: 103, name: "İncandessence", price: '2 manat' },
    { id: 104, name: "Yara", price: '2 manat' },
    { id: 105, name: "Prada Candy", price: '1 manat' },
    { id: 106, name: "Bergamot", price: '1.5 manat' },
    { id: 107, name: "Shaik Deluxe", price: '4 manat' },
    { id: 108, name: "Shaik Sadə", price: '1.5 manat' },
    { id: 109, name: "Pitter Peach", price: '2 manat' },
    { id: 110, name: "Lost Cherry", price: '2 manat' },
    { id: 111, name: "Delina", price: '2 manat' },
    { id: 112, name: "Megamare Delux", price: '5 manat' },
    { id: 113, name: "Megamare Sadə", price: '3 manat' },
    { id: 114, name: "Kirke (T.Trezza)", price: '1.5 manat' },
    { id: 115, name: "Andromeda (T.T)", price: '2 manat' },
    { id: 116, name: "Gumin", price: '2 manat' },
    { id: 117, name: "Silver", price: '1.5 manat' },
    { id: 118, name: "Cartier Declaration", price: '1.5 manat' },
    { id: 119, name: "Cartier Panthere", price: '1.5 manat' },
    { id: 120, name: "African Leather", price: '2 manat' },
    { id: 121, name: "Molecule 04", price: '1 manat' },
    { id: 122, name: "Molecule 05", price: '2 manat' },
    { id: 123, name: "Molecule 0.1", price: '1.5 manat' },
    { id: 124, name: "Givenchy Escapade", price: '1.5 manat' },
    { id: 125, name: "Dior Savage Fransa", price: '2 manat' },
    { id: 126, name: "Dior Savage Sadə", price: '1.5 manat' },
    { id: 127, name: "Miss Dior Blooming", price: '1.5 manat' },
    { id: 128, name: "Xerjoff Sadə", price: '1.5 manat' },
    { id: 129, name: "Xerjoff Delux", price: '4 manat' },
    { id: 130, name: "Xerjoff Gran Ballo", price: '2 manat' },
    { id: 131, name: "Xerjoff Noxos", price: '2 manat' },
    { id: 132, name: "Narcotique", price: '3 manat' },
    { id: 133, name: "Bulgari Atlantique", price: '1.5 manat' },
    { id: 134, name: "Ajmal Qafiya", price: '2 manat' },
    { id: 135, name: "Ajmal Amber Wood", price: '2 manat' },
    { id: 136, name: "Gucci bamboo", price: '1.5 manat' },
    { id: 137, name: "Gucci Guilty Men", price: '1 manat' },
    { id: 138, name: "Gucci Woman Guilty", price: '1.5 manat' },
    { id: 139, name: "Gucci Flora", price: '2 manat' },
    { id: 140, name: "Dupont", price: '1 manat' },
    { id: 141, name: "Afnan Tribute Delux", price: '4 manat' },
]